name: wh_dev merge development  
on:
  push:
    branches:
      - development
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Merge origin development to wh_dev
        run: |
          git config --global user.name 'SturdyCat'
          git config --global user.email '43430109@qq.com'
          git checkout development
          git push origin development:wh_dev -f
